name: worflow to destroy the infra
on:
  workflow_dispatch: # gives a button in github ui to run the workflow

jobs:
  terraform_init:
    name: Destroy Infra
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: ap-south-1 

      - name: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: 1.7.5

      - name: Terraform Init
        id: init
        run: terraform init

        # Run a terraform fmt to check syntax
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

        # Run a terraform validate
      - name: Terraform Validate
        id: validate
    # Run even if formatting fails
        if: success() || failure()
        run: terraform validate -no-color
     
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        